// Dummy data for frontend development
// This allows the frontend to work independently from the backend

export const dummyUsers = {
  admin: {
    id: 1,
    email: 'admin@nutriplan.com',
    password: 'admin123',
    full_name: 'Admin User',
    role: 'admin',
  },
  user: {
    id: 2,
    email: 'user@nutriplan.com',
    password: 'user123',
    full_name: 'John Doe',
    role: 'user',
  },
};

export const dummyHealthProfile = {
  id: 1,
  user_id: 2,
  age: 28,
  gender: 'male',
  height_cm: 175,
  weight_kg: 75,
  neck_cm: 38,
  waist_cm: 85,
  hip_cm: 95,
  activity_level: 'moderate',
  bmi: 24.49,
  bmr: 1731.25,
  tdee: 2683.44,
  body_fat_pct: 18.5,
};

export const dummyFoods = [
  {
    id: 1,
    name: 'Grilled Chicken Salad',
    category: 'restaurant',
    calories: 350,
    protein_g: 35,
    carbs_g: 15,
    fat_g: 12,
    price: 12.99,
    image_url: 'https://images.pexels.com/photos/2097090/pexels-photo-2097090.jpeg?auto=compress&cs=tinysrgb&w=400',
    is_active: true,
  },
  {
    id: 2,
    name: 'Salmon Quinoa Bowl',
    category: 'restaurant',
    calories: 480,
    protein_g: 32,
    carbs_g: 48,
    fat_g: 18,
    price: 15.99,
    image_url: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=400',
    is_active: true,
  },
  {
    id: 3,
    name: 'Mediterranean Wrap',
    category: 'restaurant',
    calories: 420,
    protein_g: 22,
    carbs_g: 52,
    fat_g: 14,
    price: 11.99,
    image_url: 'https://images.pexels.com/photos/1659438/pexels-photo-1659438.jpeg?auto=compress&cs=tinysrgb&w=400',
    is_active: true,
  },
  {
    id: 4,
    name: 'Vegetable Stir Fry',
    category: 'restaurant',
    calories: 320,
    protein_g: 12,
    carbs_g: 45,
    fat_g: 10,
    price: 10.99,
    image_url: 'https://images.pexels.com/photos/1640770/pexels-photo-1640770.jpeg?auto=compress&cs=tinysrgb&w=400',
    is_active: true,
  },
  {
    id: 5,
    name: 'Beef Burger',
    category: 'restaurant',
    calories: 620,
    protein_g: 38,
    carbs_g: 55,
    fat_g: 28,
    price: 13.99,
    image_url: 'https://images.pexels.com/photos/1639557/pexels-photo-1639557.jpeg?auto=compress&cs=tinysrgb&w=400',
    is_active: true,
  },
  {
    id: 6,
    name: 'Chicken Pasta',
    category: 'restaurant',
    calories: 550,
    protein_g: 28,
    carbs_g: 68,
    fat_g: 16,
    price: 14.99,
    image_url: 'https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg?auto=compress&cs=tinysrgb&w=400',
    is_active: true,
  },
  {
    id: 7,
    name: 'Greek Salad',
    category: 'restaurant',
    calories: 280,
    protein_g: 8,
    carbs_g: 18,
    fat_g: 20,
    price: 9.99,
    image_url: 'https://images.pexels.com/photos/1213710/pexels-photo-1213710.jpeg?auto=compress&cs=tinysrgb&w=400',
    is_active: true,
  },
  {
    id: 8,
    name: 'Turkey Sandwich',
    category: 'restaurant',
    calories: 380,
    protein_g: 24,
    carbs_g: 42,
    fat_g: 12,
    price: 10.99,
    image_url: 'https://images.pexels.com/photos/1199957/pexels-photo-1199957.jpeg?auto=compress&cs=tinysrgb&w=400',
    is_active: true,
  },
  {
    id: 9,
    name: 'Whole Wheat Bread',
    category: 'bakery',
    calories: 120,
    protein_g: 4,
    carbs_g: 22,
    fat_g: 2,
    price: 3.99,
    image_url: 'https://images.pexels.com/photos/1775043/pexels-photo-1775043.jpeg?auto=compress&cs=tinysrgb&w=400',
    is_active: true,
  },
  {
    id: 10,
    name: 'Chocolate Croissant',
    category: 'bakery',
    calories: 280,
    protein_g: 6,
    carbs_g: 38,
    fat_g: 14,
    price: 4.99,
    image_url: 'https://images.pexels.com/photos/2135677/pexels-photo-2135677.jpeg?auto=compress&cs=tinysrgb&w=400',
    is_active: true,
  },
  {
    id: 11,
    name: 'Blueberry Muffin',
    category: 'bakery',
    calories: 320,
    protein_g: 5,
    carbs_g: 48,
    fat_g: 12,
    price: 4.49,
    image_url: 'https://images.pexels.com/photos/2067396/pexels-photo-2067396.jpeg?auto=compress&cs=tinysrgb&w=400',
    is_active: true,
  },
  {
    id: 12,
    name: 'Cinnamon Roll',
    category: 'bakery',
    calories: 420,
    protein_g: 7,
    carbs_g: 58,
    fat_g: 18,
    price: 5.49,
    image_url: 'https://images.pexels.com/photos/2135677/pexels-photo-2135677.jpeg?auto=compress&cs=tinysrgb&w=400',
    is_active: true,
  },
  {
    id: 13,
    name: 'Bagel with Cream Cheese',
    category: 'bakery',
    calories: 350,
    protein_g: 12,
    carbs_g: 52,
    fat_g: 10,
    price: 5.99,
    image_url: 'https://images.pexels.com/photos/1775043/pexels-photo-1775043.jpeg?auto=compress&cs=tinysrgb&w=400',
    is_active: true,
  },
  {
    id: 14,
    name: 'Banana Bread',
    category: 'bakery',
    calories: 280,
    protein_g: 4,
    carbs_g: 45,
    fat_g: 10,
    price: 4.99,
    image_url: 'https://images.pexels.com/photos/830894/pexels-photo-830894.jpeg?auto=compress&cs=tinysrgb&w=400',
    is_active: true,
  },
  {
    id: 15,
    name: 'Apple Danish',
    category: 'bakery',
    calories: 310,
    protein_g: 5,
    carbs_g: 42,
    fat_g: 14,
    price: 4.79,
    image_url: 'https://images.pexels.com/photos/2135677/pexels-photo-2135677.jpeg?auto=compress&cs=tinysrgb&w=400',
    is_active: true,
  },
  {
    id: 16,
    name: 'Sourdough Loaf',
    category: 'bakery',
    calories: 140,
    protein_g: 5,
    carbs_g: 28,
    fat_g: 1,
    price: 6.99,
    image_url: 'https://images.pexels.com/photos/1775043/pexels-photo-1775043.jpeg?auto=compress&cs=tinysrgb&w=400',
    is_active: true,
  },
];

export const dummyOrders = [
  {
    id: 1,
    user_id: 2,
    customer_name: 'John Doe',
    contact_number: '+1234567890',
    delivery_address: '123 Main St, City',
    total_amount: 45.97,
    order_status: 'delivered',
    created_at: '2025-12-28T10:30:00Z',
    items: [
      { food_id: 1, food_name: 'Grilled Chicken Salad', quantity: 2, price: 12.99 },
      { food_id: 9, food_name: 'Whole Wheat Bread', quantity: 3, price: 3.99 },
    ],
  },
  {
    id: 2,
    user_id: 2,
    customer_name: 'John Doe',
    contact_number: '+1234567890',
    delivery_address: '123 Main St, City',
    total_amount: 28.98,
    order_status: 'confirmed',
    created_at: '2025-12-30T14:20:00Z',
    items: [
      { food_id: 2, food_name: 'Salmon Quinoa Bowl', quantity: 1, price: 15.99 },
      { food_id: 10, food_name: 'Chocolate Croissant', quantity: 2, price: 4.99 },
    ],
  },
  {
    id: 3,
    user_id: null,
    customer_name: 'Guest User',
    contact_number: '+1234567892',
    delivery_address: '789 Pine Rd, Village',
    total_amount: 33.96,
    order_status: 'pending',
    created_at: '2025-12-31T09:15:00Z',
    items: [
      { food_id: 5, food_name: 'Beef Burger', quantity: 1, price: 13.99 },
      { food_id: 11, food_name: 'Blueberry Muffin', quantity: 3, price: 4.49 },
    ],
  },
];

export const dummyMealPlans = [
  {
    id: 1,
    user_id: 2,
    goal_type: 'lose',
    target_weight_change: 1.5,
    start_date: '2025-01-01',
    end_date: '2025-01-14',
    daily_calorie_target: 2100,
    created_at: '2025-12-31T08:00:00Z',
  },
];

export const dummyStats = {
  totalOrders: 15,
  totalRevenue: 1245.50,
  totalFoods: 16,
  totalUsers: 42,
  pendingOrders: 3,
  confirmedOrders: 5,
  deliveredOrders: 7,
};
